config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'games#index'
  resources :games 
  get '/games_list', to: 'games#list', as: 'games_list'
  resources :players 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  validates :name, presence: true, length: {minimum: 3, maximum: 15}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController 
  before_action :set_game, only: [:show]
  def index 
  end 

  def new 
    game = Game.new() 
    if game.save 
      session[:game] = game.id 
      session[:new_game] = true 
      redirect_to new_player_path 
    else  
      puts game.errors.full_messages 
    end
  end 

  def show 
  end

  private 
  def set_game 
    @game = Game.find_by_id(params[:id]) 
  end 
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new 
    @player = Player.new() 
  end

  def create 
    primary = session[:new_game] ? true : false 
    game = Game.find_by_id(session[:game])
    the_params = set_player 
    the_params[:game] = game
    player = Player.new(the_params)
    if player.save 
      session[:player] = player.id 
      redirect_to controller: 'games', action: 'show', id: game.id 
    else  
      puts player.errors.full_messages 
    end
  end

  private
  def set_player
    params.require(:player).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/games/index.html.erb
<h1>This is index page </h1> 
<%= link_to "New Game", new_game_path %> 
<br>
<%= link_to "Join a Game", games_list_path %>

app/views/games/show.html.erb
<h1> This is Games show page </h1> 

<%= @game.id %>
<%= Player.find_by_id(session[:player]).name %>
<% if session[:new_game] %>
  Waiting for player 2  
<% else %> 
  player 2 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TickTakToe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/new.html.erb
<%= form_with model: @player do |form| %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>